[project]
name = "chesnok-uz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argon2>=0.1.10",
    "argon2-cffi>=25.1.0",
    "dotenv>=0.9.9",
    "fastapi[standart]>=0.128.0",
    "httpx>=0.28.1",
    "jose>=1.0.0",
    "jwt>=1.4.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.11",
    "python-jose[cryptography]>=3.5.0",
    "redis>=7.2.0",
    "redis-cli>=1.0.1",
    "ruff>=0.14.14",
    "starlette>=0.50.0",
    "starlette-admin>=0.16.0",
    "unicode>=2.9",
    "uvicorn>=0.40.0",
    "xmltodict>=1.0.2",
]
