"""change relationship

Revision ID: 46dcaead87d8
Revises: d0ae836f49b8
Create Date: 2026-01-27 10:20:16.165949

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "46dcaead87d8"
down_revision: Union[str, Sequence[str], None] = "d0ae836f49b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
