"""change relationship

Revision ID: 78a2f72a2f66
Revises: fb01587d4e98
Create Date: 2026-01-27 09:28:54.475267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78a2f72a2f66"
down_revision: Union[str, Sequence[str], None] = "fb01587d4e98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("avatar_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        None, "user", "media", ["avatar_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "avatar_id")
    # ### end Alembic commands ###
