"""change relationship

Revision ID: ade700bac570
Revises: e93159aa4537
Create Date: 2026-01-27 09:38:43.036688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ade700bac570"
down_revision: Union[str, Sequence[str], None] = "e93159aa4537"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "post_count", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column(
        "user", "post_read_count", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column("user", "post_read_count", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("user", "post_count", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###
