"""change relationship

Revision ID: d0ae836f49b8
Revises: e48353e815aa
Create Date: 2026-01-27 10:16:12.938743

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d0ae836f49b8"
down_revision: Union[str, Sequence[str], None] = "e48353e815aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
