"""change relationship

Revision ID: e93159aa4537
Revises: 78a2f72a2f66
Create Date: 2026-01-27 09:31:27.446627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e93159aa4537"
down_revision: Union[str, Sequence[str], None] = "78a2f72a2f66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "post_count", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("user", "post_read_count", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "post_read_count", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column("user", "post_count", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
